# Generated by Django 3.1.2 on 2020-11-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='main_full_name',
        ),
    ]
