# Generated by Django 3.1.2 on 2020-11-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='quizz',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
