# Generated by Django 3.1.2 on 2020-11-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service_name',
            new_name='service_id',
        ),
    ]
